/**
 * Human-readable labels for section content version metadata.
 * Uses only persisted model_used / approval_status fields.
 */

export function describeVersionSource(modelUsed: string | null | undefined): string {
  if (!modelUsed) return 'Generated by Rami';
  if (modelUsed.includes('restored-from-v')) {
    const match = modelUsed.match(/restored-from-v(\d+)/);
    return match ? `Restored from version ${match[1]}` : 'Restored from earlier version';
  }
  if (modelUsed.endsWith('+manual-edit') || modelUsed.includes('+manual-edit')) {
    return 'Edited manually';
  }
  if (modelUsed.endsWith('+ai-edit') || modelUsed.includes('+ai-edit')) {
    return 'Edited with Rami';
  }
  return 'Generated by Rami';
}

export function describeVersionStatus(input: {
  version: number;
  approvalStatus: string;
  isCurrent: boolean;
}): string {
  if (input.isCurrent && input.approvalStatus === 'APPROVED') {
    return 'Current approved';
  }
  if (input.isCurrent) {
    return 'Current draft';
  }
  if (input.approvalStatus === 'APPROVED') {
    return 'Approved (historical)';
  }
  if (input.version === 1) {
    return 'Initial generation';
  }
  return 'Draft';
}
